# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Get_sub_watersheds": "01_Virtual_data_setup.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/nbdev_template/"

git_url = "https://github.com/fastai/nbdev_template/tree/master/"

def custom_doc_links(name): return None
