# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Get_sub_watersheds": "00_core.ipynb",
         "cascade_values_async": "00_core.ipynb",
         "cascade_values_sync": "00_core.ipynb",
         "colors": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://nicolas998.github.io/param_ident/"

git_url = "https://github.com/nicolas998/param_ident/tree/master/"

def custom_doc_links(name): return None
